### ISSUE TITLE
Visibility?

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#13]
Should we use `withVisible()` and optionally hide invisible output (via an argument to `rig()`)? This solves part of #12.

**Comment by moodymudskipper** [comment]
Good idea, probably not often so useful since we have #12, but I can imagine that some other side effect functions might clutter the output too much in some cases.

This now works : 

``` r
boomer::boom(options(foo = 1+1))
#> 1 + 1
#> [1] 2
#> options(foo = 1 + 1)
#> $foo
#> NULL

boomer::boom(options(foo = 1+1), visible_only = TRUE)
#> 1 + 1
#> [1] 2
```

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

d02a04fd1e5d4f29057afba6750b217d1aa9cb2a

**Comment by moodymudskipper** [comment]
I think this can be closed now
