### ISSUE TITLE
Roll own all.names() implementation

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#19]
because `base` and `head` really shouldn't be part of this:

``` r
all.names(quote(base::head(3)))
#> [1] "::"   "base" "head"
```

<sup>Created on 2021-05-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Not sure if this counts as documented behavior of `all.names()` .

I wonder if we should memoise `double_colon()` and `triple_colon()`, because wrapping occurs at run time here?

**Comment by moodymudskipper** [comment]
I think with current implementation base and head would be overridden if they existed in namespace or parents and were functions, and so we indeed would shim them for nothing. I don't know if it hurts other than for minor performance impact but if your proposal tightens the code why not. 
I might be missing something. 

What would be the benefit of memoising those functions?

**Comment by krlmlr** [comment]
The linked pull request fails with current `all.names()` .

When memoising, running boomed/rigged code will be a little faster, we won't need to wrap every time.

**Comment by moodymudskipper** [comment]
Is this your use case ?

``` r
foo1 <- function(x) {
  x <- x * 2
  SQRT(x)
}
foo1(2)
#> Error in SQRT(x): could not find function "SQRT"
boomer::rig(foo1)()
#> Not rigging undefined `SQRT()`.
#> Error in rlang::eval_bare(sc, parent.frame()): argument "x" is missing, with no default
```

There would be other cases that we'd need to address

------------------

```
foo2 <- function(x) {
  x <- x * 2
  SQRT <- sqrt
  SQRT(x)
}
foo2(2)
#> [1] 2
boomer::rig(foo2)(2)
#> x * 2
#> [1] 4
#> [1] 2
```

Here in`foo2()`, `SQRT` is found by "all.vars" so `SQRT` is skipped before the existence test, so we don't mention SQRT not being rigged, if we used `getParseData()` instead of `all.names()` and `all.vars()` we might be explicit about skipping it. 


Possible fix :

In order to actually not skip it and show `SQRT(x)` we might override `<-`, `=`, `assign` in the closure env so that when assigning a function, they `wrap()` it beforehand. 

------------

```
foo3 <- function(x) {
  x <- x * 2
  assign("SQRT", sqrt)
  SQRT(x)
}
foo3(2)
#> [1] 2
boomer::rig(foo3)()
#> Not rigging undefined `SQRT()`.
#> Error in rlang::eval_bare(sc, parent.frame()): argument "x" is missing, with no default
```

Here in`foo3()`, `SQRT` is not found by "all.vars" so `SQRT` is not skipped before the existence test, the existence test doesn't find it in the closure environment so an inaccurate message is displayed. 

This might be dealt with by the proposed fix for `foo2` above if we override assign too. But ùaybe overriding `assign` is overkill, it's seldom used to assign in current envir and anyway we can't be 100% robust here because functions theoretically could be created through the side effects of any functions.

---------------------------------

``` r
foo4 <- function() {
  sqrt(4)
  lapply(c(4,9), sqrt)
}
foo4()
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
boomer::rig(foo4)()
#> c(4, 9)
#> [1] 4 9
#> lapply(c(4, 9), sqrt)
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3

```

Here in `foo4` sqrt is found by `all.vars` in the lapply call, so it is skipped. This will be solved by an alternate implementation of all.names but then we'd face the issue in foo5 below :

-----------------------

```
foo5 <- function() {
  sqrt(4)
  lapply(c(4,9), "sqrt")
}
foo5()
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
boomer::rig(foo5)()
#> sqrt(4)
#> [1] 2
#> c(4, 9)
#> [1] 4 9
#> FUN(X[[i]], ...)
#> [1] 2
#> FUN(X[[i]], ...)
#> [1] 3
#> lapply(c(4, 9), "sqrt")
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
#> [[1]]
#> [1] 2
#> 
#> [[2]]
#> [1] 3
```

Here in `foo5` sqrt is NOT found by `all.vars` since the lapply call uses a string, but it is found by `all.names` (and will be by our own implementation), thus it is shimmed. The lapply call then uses it too and we get this confusing output.

This would be fixed if shimmed functions were checking where they're called from before applying their side effects.
That is, their caller environment must be a child of the masking environment.

----------------------------------------------

So overall I see main 3 actions to improve current implementation : 

* detect functions based on  `getParseData()` to avoid skipping functions used also as variable names
* override `<-` and `=`, so calls to locally defined functions can be boomed too
* cancel side effects in shimmed function if it's not called from the rigged function's execution environment.

**Comment by moodymudskipper** [comment]
`fetch_functions` was implemented 1d7a04370b14508df5f4d1ca2aa37335e15421d6

**Comment by moodymudskipper** [comment]
We can now boom functions defined at runtime with `<-` or `=`

``` r
foo2 <- function(x) {
  x <- x * 2
  SQRT <- sqrt
  SQRT(x)
}
foo2(2)
#> [1] 2
boomer::rig(foo2)(2)
#> Not rigging undefined `SQRT()`.
#> x * 2
#> [1] 4
#> SQRT(x)
#> [1] 2
#> [1] 2
```

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The message "Not rigging undefined `SQRT()`" is probably obsolete, we might encounter functions that won't be found AND are not defined through `<-` or `=` but I expect that these will be extremely rare. If it's the case the message can be removed, otherwise we could have a message that says "The functions foo, bar, and baz were not found in <envir>, they might be boomed at runtime, or will be skipped", but it might be a bit intimidating and rarely useful.

**Comment by moodymudskipper** [comment]
I could "solve" `foo5` by having the wrapped function do some environment checks but it has the unfortunate side effect of not exploding the calls provided to NSE functions like `subset`. I don't think it's acceptable, it's a nice feature... OTOH we can't afford to have lapply calls print something at each iteration. need a new idea/approach.

**Comment by moodymudskipper** [comment]
closing as `fetch_functions` seems to work ok
