### ISSUE TITLE
Execution time of side effects

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#34]
Should we print first, then execute?

``` r
my_print <- function(x) {
  writeLines(paste0("my: ", x))
  invisible(x)
}

boomer::boom(my_print(1 + 2))
#> · 1 + 2
#> [1] 3
#> my: 3
#> my_print(1 + 2)
#> [1] 3
```

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I believe `my: 3` should come below the `my_print()` call, this has confused me a few times in the past.

**Comment by moodymudskipper** [comment]
If we print first then execute we'll have all nested calls first then all outputs.

What we might do is capture the output and print it after, that would be consistent with what you proposed with errors in https://github.com/moodymudskipper/boomer/commit/98c94054ec22c19994dfed6c483e35bb4530d47e (catch and rethrow after we've printed the call). 

The problem is then we should catch messages and warnings too, and we need to rethrow them in the correct order, so we need to keep a stack of the side effects

In fact what we have with errors is already problematic in some cases since side effects can happen after `stop()` , see below the message is printed after the error in the normal case, and not in the boomed version :

``` r
foo <- function() {
  on.exit(message("a"))
  stop("b")}

foo()
#> Error in foo(): b
#> a

boomer::boom(foo())
#> a
#> foo()
#> Error: simpleError/error/condition
#> Error in (function () : b
```

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


The line `#> my_print(1 + 2)` should really be understood as "exiting my_print", and the line "entering my_print" is omitted.

**Comment by moodymudskipper** [comment]
Is it more intuitive this way ?

![image](https://user-images.githubusercontent.com/18351714/121426914-6a324200-c974-11eb-9ccc-ef39ad803226.png)

**Comment by krlmlr** [comment]
I'm not sure. Could a newline between `[1] 3` and `my: 3` help here?

**Comment by moodymudskipper** [comment]
If I understand correctly you suggest that we skip a line after each printed result ?

Note that since results can be post processed separately from side effects, so we could also have a different color (green for instance), or/And they could have a "#>" prefix (or another prefix) while side effect would stay normal.

**Comment by krlmlr** [comment]
Yes. Maybe it's sufficient to indent results?

**Comment by moodymudskipper** [comment]
better ?

![boomer1](https://user-images.githubusercontent.com/18351714/121505630-49550580-c9e3-11eb-8a32-3bd9f9c618c6.Png)
![boomer2](https://user-images.githubusercontent.com/18351714/121505635-49ed9c00-c9e3-11eb-909c-b57c27ae1910.Png)

**Comment by krlmlr** [comment]
I love it!

**Comment by moodymudskipper** [comment]
Great, thanks for pushing me and pointing me to `withr::defer`, I would have given up too early
