### ISSUE TITLE
Optionally print function arguments

### ISSUE THREAD

**Issue by krlmlr** [moodymudskipper/boomer#40]
I've hit a limitation of boomer today: in a sequence of functions that forward their arguments, the argument values are very hard to trace.

Motivating example:

``` r
c <- function(x) wat
b <- function(x) c(x)
b <- boomer::rig(b)
a <- function(x) b(3)

a(5)
#> 👇 b
#> 💣 c
#> 💥 c(x)
#> Error: simpleError/error/condition
#> Error in (function (x) : object 'wat' not found
#> 👆 b
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

How can we enhance the output so that we learn from it that `x` is 3 in the `c(x)` call? Can we enhance `rig()` in a way that it (optionally) prints its arguments? Maybe we can print only those arguments that were actually forced by the function call, to avoid NSE issues?

**Comment by moodymudskipper** [comment]
It's tricky, I might have an idea (not the full path though), a bit crazy but I think it will need to be.

We could set all the arguments as active binding in the parent environment (the mask containing all the other shims), and build a function without arguments so it would fetch the argument values above and trigger the printing, the NSE arguments wouldn't be triggered so wouldn't fail.   
In theory even `...` can be made into an active binding returning a dot object.

One problem is that I'm not sure we can get `substitute`, `enquo` etc to work on those.

The easy workaround is to `force(x)` in `c`'s code.

A different feature that would solve this case would be to display optionally the values of the variables of the execution environment on exit (using `with_defer` in the first called function again).

**Comment by krlmlr** [comment]
I don't necessarily have control over `c()`, e.g. if it lives in another package.

I see how it's tricky. Printing on exit sounds like the most appealing solution. It still will print after the function's side effects, but for pure functions it doesn't really matter. Can we print only the arguments where the promise has been resolved, does lobstr/pryr have features that help us here, or do we need to roll our own?

**Comment by moodymudskipper** [comment]
From the first wrapped call we can fetch the argument names, then use with_defer to test them on exit with pryr::is_promise .

The arguments might have changed value though, so better would be to be able to fetch the pryr::promise_info of the args when entering the first wrapped call, then try() to evaluate them, then set build promises back using delayedAssign(). 

A corner case is that if evaluating the argument has side effects they'd be run twice, this would be rare though and can be documented with the option, and might be mitigated for some side effects.

**Comment by moodymudskipper** [comment]
![image](https://user-images.githubusercontent.com/18351714/122107616-8ffb9300-ce1b-11eb-8816-1c8783777d4a.png)

b57da83f7d44856c7d5436df6a23e8a4c09ba6c8

Finally I don't display on exit but when entering the first call of the rigged function.

From the doc : 

> Arguments are not always meant to be evaluated if non standard
 evaluation is used, if `print_args` is `TRUE` we always try to evaluate them.
 Promises are not affected so calls to `substitute()` or `rlang::enquo()` for instance
 will work fine.
 However pure NSE arguments will be evaluated once instead of not evaluated at all,
 and SE arguments will be evaluated twice instead of once. So in the rare case where a function
 has an argument whose evaluation has side effects the behavior might be unexpected.
 Simple side effects such as printing, messaging, warning or failing are silenced when
 evaluating arguments the first time.

How does it look @krlmlr ?

**Comment by krlmlr** [comment]
Looks great, thanks! Can we force the promise instead of evaluating it, to avoid double evaluation?

(I briefly considered masking/overriding `{` and calling the wrapped function as `wrapped_fun({{ arg_1 }})`, this seems to add more problems than it solves.)

**Comment by moodymudskipper** [comment]
I haven't found a way to force a promise and still have `substitute()` work.

I have another idea now though, each wrapped functions might check if the rigged function's arguments are promises before and after calling the original function. If it changes we print it as we do now. We'd write the value of the evaluated arg right before the call that evaluates it.

**Comment by krlmlr** [comment]
Checking promiseness after evaluation sounds great!

**Comment by krlmlr** [comment]
IIUC, this avoids double evaluation?

**Comment by moodymudskipper** [comment]
Yes, it's much more working "with" R while the current solution works "against it".

The arg value might be displayed in the middle of a rigged block (rather than at the start) with more indentation but I think it's fine, even educational about delayed evaluation which is not obvious to grasp

**Comment by moodymudskipper** [comment]
It works (though I'm not totally confident in the robustness). However, this doesn't help for the motivating example, because `x` is never evaluated.

![image](https://user-images.githubusercontent.com/18351714/122649279-64cfb700-d12d-11eb-80df-5ed7778900da.png)
 
An additional feature would be to print on exit in case of failure, but we can do several things here : 

* print unevaled arguments (if we can evaluate them)
* print all arguments (a bit tricky because might have been overriden, we'll need to backup the values when we check that the promises are evaled)
* print full execution environment
* provide a function like `traceback()` which would do some of the above, so we print extra on the error only if we really want to

A caveat when trying to eval args that were not evaled when error occured is that they might not be meant to be evaled at this point (or ever) , BUT might be evaled anyway and have undesireable side effects if evaled in the `parent.frame()` as if they'd been forced. Too far fetched ?

**Comment by moodymudskipper** [comment]
Regarding the working use case, I wonder if it should be default, I think it's generally useful.

**Comment by krlmlr** [comment]
Looks good (except for the pryr message):

``` r
c <- function(x) {
  if (x > 0) wat
}
b <- function(x) c(x)
b <- boomer::rig(b, print_args = TRUE)
a <- function(x) b(3)

a(5)
#> 👇 b
#> 💣 c
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
#> x :
#> [1] 3
#> 💥 c(x)
#> Error: simpleError/error/condition
#> Error in (function (x) : object 'wat' not found
#> 👆 b
```

<sup>Created on 2021-06-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I don't think we should ever force unevaluated promises, there's no way their value can influence the error. The *expression* could, but we already print the expression used in the call.

We could state that boomer works best for functional code that never overwrites variables. Should we special-case `<-` and `=` so that the old value is shown?

**Comment by moodymudskipper** [comment]
> I don't think we should ever force unevaluated promises, there's no way their value can influence the error. The expression could, but we already print the expression used in the call.

Makes sense

> Should we special-case <- and = so that the old value is shown, if it's available and forced in the target environment?

Do you have a use case in mind where it is useful ? The rhs of `=` and `<-` is printed already and we can now print arguments when they're forced, so it seems to me this would duplicate the output.

It makes me think of another possible feature though, we might signal it when we override a variable accessible in a parent env (but I'm not sure if the new value is useful), i.e. signal if `exists("var") && !exists("var", exec_env)`

**Comment by moodymudskipper** [comment]
One the use case above is clarified, we might open a new issue, I think the main one here is resolved
